apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  database_url: avis-bdd.local
  nameAdmin: root

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configmap
data:
  port: "27017"
  host: mongodb-service

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: front-configmap
data:
  host: node-back-service
  port: "8000"


