apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-back
spec:
  selector:
    matchLabels:
      app: node-back
  template:
    metadata:
      labels:
        app: node-back
    spec:
      containers:
      - name: node-back
        image: loakzoggo/node-back
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
          - name: MONGODB_HOST
            valueFrom: 
              configMapKeyRef:
                name: node-configmap
                key: host
          - name: MONGODB_PORT
            valueFrom:
              configMapKeyRef:
                name: node-configmap
                key: port
          - name: MONGODB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: nameAdmin
          - name: MONGODB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: password

---

apiVersion: v1
kind: Service
metadata:
  name: node-back-service
spec:
  selector:
    app: node-back
  ports:
  - port: 8000
    targetPort: 8000

