apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite
spec:
  selector:
    matchLabels:
      app: react-vite
  template:
    metadata:
      labels:
        app: react-vite
    spec:
      containers:
      - name: react-vite
        image: loakzoggo/react-vite
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: react-vite-service
spec:
  selector:
    app: react-vite
  type: NodePort
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30001